### PR TITLE
Allow providing GeoIP license key in Dockerfile

### PR DESCRIPTION
**Pull request by SuperSandro2000**
This allows you to provide a geoip license key shown in the readme to build a docker image with the geoip dbs.

### CODE REVIEW

**Comment by maximbaz** [comment]
I'm not sure it's a good idea to put databases inside the Docker image... I think the idea is to use `make geoip-download` outside and mount the databases in the image as a volume.

**Comment by SuperSandro2000** [comment]
Why not?

This would require me to have make and curl on the target machine installed instead of building it on a builder and pushing it to some production node. Also this data is not changing in production so I don't need to have a volume.

Also the key is not stored in the image and as long as you don't push the image I don't see any tos violations.

**Comment by maximbaz** [comment]
Not saying that what you are doing is wrong, if it suits your needs it's okay 👍 , just sharing an impression that this might be too specific to your own use-case and might not be something that the general public needs... I'll leave it to mpolden and you to decide 🙂 


> this data is not changing in production so I don't need to have a volume.

Databases are being updated, more frequently than `echoip` is

> This would require me to have make and curl on the target machine installed

If this was the only thing stopping you, you have docker installed on your target machine, I'm sure this can be worked around 🙂

**Comment by mpolden** [comment]
Thanks, but I agree with @maximbaz here.

**Pull request closed without merging**
