### PR TITLE
Created a dark theme for index.html

### PR DESCRIPTION
**Pull request by superjeng1**
I created a dark theme for index.html, and as a bonus, I added wrapping in dark-index.html so the site won't break if the window is too small.

### CODE REVIEW

**Comment by jacobhaug** [comment]
Personally, I think you should just keep one `index.html` file. I would instead use a media selector to target dark mode. (`prefers-color-scheme: dark`) I tested this selector and it works in the latest version of Chrome, Firefox, and Safari on Mac. (https://css-tricks.com/dark-modes-with-css/)

So, you'd do something like....

```
@media (prefers-color-scheme: dark) {
  html,
  .pure-g [class*='pure-u'],
  a {
    background-color: #161719;
    color: #d8d9da;
  }
  .ip {
    border: 1px solid #313233;
    background: #212223;
  }
  .footer {
    color: #8e8e8e !important;
  }
  a {
    background: #313233;
  }
  a:hover,
  active {
    background: #3d3e3f;
  }
}
```

**Comment by maximbaz** [comment]
Just tested, works for me on Linux as well, so +1 for `prefers-color-scheme: dark`

**Comment by superjeng1** [comment]
Thanks for the great tip! I removed the second index.html and changed the index.html accordingly. But, should we default dark mode or light mode? As https://css-tricks.com/dark-modes-with-css/ pointed out, it is possible to default dark mode, but should we?

**Comment by maximbaz** [comment]
I'd probably keep light theme as default just not to introduce breaking changes, but I don't mind either way 😉

**Pull request merged**
