### PR TITLE
Detect if sudo is needed for docker commands

### PR DESCRIPTION
**Pull request by SuperSandro2000**
With this I can just run the ``make docker-build`` even when I am not in the docker group and I just get prompted for my sudo password.

### CODE REVIEW

**Comment by maximbaz** [comment]
This seems like an overkill to do in each and every Dockerfile in the world.... Have you considered making a wrapper for yourself instead that will ask for sudo password?

For example, put the script below in `/usr/local/bin/` (assuming it is in your PATH and is defined earlier than `/usr/bin/`):

```sh
#!/bin/sh

sudo -E /usr/bin/docker "$@"
```

**Comment by SuperSandro2000** [comment]
Than autocomplete and the help would need sudo rights, too which I do not want. Also I don't want to modify my system docker behavior. I could put my script from .bash_aliases to ~/.local/bin which then also would work in make. Still does would help all people which are logged into some docker registry with their normal user and want to build this image.

**Comment by mpolden** [comment]
This is too specific to your particular environment. If you want to replace the `docker` command with a variable  (e.g. add `DOCKER ?= docker` at the top) which you can then override to whatever you want, I'm fine with that.

**Comment by SuperSandro2000** [comment]
> This is too specific to your particular environment.

In fact not really. It just detects if the current user is in the docker group in which case sudo wouldn't be needed and then it keeps all docker and docker-compose relevant ENVs and runs docker with sudo. Very very generic and should basically work everywhere without thinking about it for a second.

**Comment by SuperSandro2000** [comment]
> If you want to replace the docker command with a variable (e.g. add DOCKER ?= docker at the top) which you can then override to whatever you want, I'm fine with that.

Well, I ended up doing that in https://github.com/mpolden/echoip/pull/89

**Pull request closed without merging**
