### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by maximbaz**
I want to make your awesome project very easy to deploy. A big step forward would be to have an always up-to-date Docker image on Docker Hub.

In this PR I made a Dockerfile, it makes a very tiny Docker container running ipd.

The ideal solution would be to make a Travis job to publish the docker image to Docker Hub, on daily basis + when you push to `master` — that way without any action from your side, a Docker image will always be up to date.

I have already configured such workflow a couple of times for my own projects, e.g. [here](https://github.com/maximbaz/docker-arch-build-aur) and [here](https://github.com/maximbaz/docker-emojione-fonts-build). Their `.travis.yml` is almost identical, and we would need to make something similar for you too. I will help you configure this, but some parts you would need to do yourself, as I can't access your project on Travis. Do you agree to do this?

### CODE REVIEW

**Comment by kshcherban** [comment]
Doesn't work for me.
Which version of golang did you use?
```
docker build -t ipd .
Sending build context to Docker daemon  364.5kB
Step 1/9 : FROM golang:alpine AS build
alpine: Pulling from library/golang
8e3ba11ec2a2: Pull complete
8e6b2bc60854: Pull complete
3d20cafe6dc8: Pull complete
a7b6bf1e1322: Pull complete 
b95ef83a75ea: Pull complete 
Digest: sha256:499b775c0954ce029c9db806c4543524b38eeb38bc5588c3ea81bb135f8c55db
Status: Downloaded newer image for golang:alpine
 ---> cace225819dc
Step 2/9 : ADD . /go/src/github.com/mpolden/ipd
 ---> 629640c02914
Step 3/9 : WORKDIR /go/src/github.com/mpolden/ipd
Removing intermediate container 02a0851b9598
 ---> a480da0c90d0
Step 4/9 : RUN go install ./...
 ---> Running in cfb663aab929
cmd/ipd/main.go:6:2: cannot find package "github.com/jessevdk/go-flags" in any of:
        /usr/local/go/src/github.com/jessevdk/go-flags (from $GOROOT)
        /go/src/github.com/jessevdk/go-flags (from $GOPATH)
iputil/database/database.go:6:2: cannot find package "github.com/oschwald/geoip2-golang" in any of:
        /usr/local/go/src/github.com/oschwald/geoip2-golang (from $GOROOT)
        /go/src/github.com/oschwald/geoip2-golang (from $GOPATH)
The command '/bin/sh -c go install ./...' returned a non-zero code: 1
```

**Comment by maximbaz** [comment]
You are right, I forgot to fetch dependencies - updated now, thanks!

Ping @mpolden, do you have any reservations against having docker image being automatically built and pushed by Travis on every commit in master?

**Comment by mpolden** [comment]
@maximbaz Sure, having an "official" Docker image would be useful. Can you update this PR to use modules to pull down dependencies?

**Comment by maximbaz** [comment]
Done, I also fixed Go version so that it is explicit what we build against.

@mpolden do you want to configure Travis yourself to build & push Docker image, or do you want me include changes needed for .travis.yml in a new PR?

It will look more or less like this: https://github.com/maximbaz/docker-arch-build-aur/blob/master/.travis.yml

You will need to configure secrets either in .travis.yml like I did, or directly in Travis UI.

**Comment by maximbaz** [comment]
Oh that cool, much simpler than what I was doing so far 😄

**Comment by mpolden** [comment]
The linked Docker hub procedure looks easy, but I'd rather have Travis handle building/publishing of the image and not depend on another system. I can do that in a separate commit.

@maximbaz Shouldn't the Dockerfile expose a port as suggested by @kshcherban?

**Comment by maximbaz** [comment]
That EXPOSE is just metadata and has no impact on actual Docker image, since port is documented in your README I decided not to duplicate this information.

**Comment by mpolden** [comment]
Ok, thanks! Merging.

**Comment by maximbaz** [comment]
Great, thanks!

> The linked Docker hub procedure looks easy, but I'd rather have Travis handle building/publishing of the image and not depend on another system. I can do that in a separate commit.

Keep in mind that we will push the image to Docker hub, so if their system breaks, at that time Travis will likely to fail pushing the image as well. But up to you, as long as the image is being built and pushed automatically I would be very happy 😉 

Please ping me when the image is pushed, or if you need any assistance 🙂

**Comment by maximbaz** [comment]
A friendly ping @mpolden, have you stumbled upon some issues in setting up automatic docker image push? Maybe reconsider using Docker Hub's integration, since it's a one-click setup?

https://docs.docker.com/docker-hub/builds/#create-an-automated-build

**Comment by mpolden** [comment]
@maximbaz It should be published now: https://hub.docker.com/r/mpolden/echoip/

Please test.

**Pull request merged**
